services:

  database:

    image: postgres:16

    container_name: addit-db

    environment:

      POSTGRES_DB: addit_ai

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres


    ports:

      - "5432:5432"


    volumes:
      - postgres_data:/var/lib/postgresql/data



  backend:

    build:

      context: .

      dockerfile: backend.Dockerfile


    container_name: addit-backend


    ports:
      - "8000:8000"

    volumes:
      - ./storage:/app/storage

    depends_on:

      - database


    env_file:
      - .env




  frontend:

    build:

      context: ./frontend


    container_name: addit-frontend


    ports:

      - "3000:3000"


    depends_on:

      - backend



volumes:

  postgres_data: