"""add_shorts_package_to_jobs

Revision ID: 467ffb7d5a2a
Revises: a53e3ae273be
Create Date: 2026-07-18 14:53:00.682698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467ffb7d5a2a'
down_revision: Union[str, Sequence[str], None] = 'a53e3ae273be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('shorts_package', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'shorts_package')
    # ### end Alembic commands ###
