"""add chapters path

Revision ID: 61d47387dcf2
Revises: 525c324132c4
Create Date: 2026-07-07 00:21:05.249907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d47387dcf2'
down_revision: Union[str, Sequence[str], None] = '525c324132c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('chapter_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'chapter_path')
    # ### end Alembic commands ###
