"""add creator_intelligence to jobs

Revision ID: 95b667d13842
Revises: f8ae379b0302
Create Date: 2026-07-13 15:33:11.748797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b667d13842'
down_revision: Union[str, Sequence[str], None] = 'f8ae379b0302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('creator_intelligence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'creator_intelligence')
    # ### end Alembic commands ###
