"""add_social_package_to_jobs

Revision ID: a53e3ae273be
Revises: 95b667d13842
Create Date: 2026-07-18 12:56:02.704678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53e3ae273be'
down_revision: Union[str, Sequence[str], None] = '95b667d13842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('social_package', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'social_package')
    # ### end Alembic commands ###
