from enum import Enum

class JobStatus(str, Enum):
    UPLOADED = "UPLOADED"
    AUDIO_EXTRACTED = "AUDIO_EXTRACTED"
    TRANSCRIBED = "TRANSCRIBED"
    CONTENT_GENERATED = "CONTENT_GENERATED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    QUEUED = "QUEUED"